CREATE DATABASE ECOMMERCE_DATA;

USE ECOMMERCE_DATA;

SELECT * FROM ECOMMERCE_DATA;

ALTER TABLE ECOMMERCE_DATA
DROP COLUMN CUSTOMERNAME, EMAIL, PH1NUMBER, PINCODE, ORDERAMOUNT, FINALAMOUNT, REVIEWTEXT, RETURNREASON;

SELECT * FROM ECOMMERCE_DATA
WHERE PurchaseDate IS NULL;

SELECT * FROM ECOMMERCE_DATA
WHERE DeliveryDate IS NULL;

SELECT * FROM ECOMMERCE_DATA
WHERE Discount IS NULL;

SELECT * FROM ECOMMERCE_DATA
WHERE Order_Amount IS NULL;

SELECT * FROM ECOMMERCE_DATA
WHERE Final_Amount IS NULL;

SELECT * FROM ECOMMERCE_DATA
WHERE Rating IS NULL;

SELECT * FROM ECOMMERCE_DATA
WHERE ComplaintRaised IS NULL;

SELECT * FROM ECOMMERCE_DATA
WHERE ResolutionStatus IS NULL;

SELECT DISTINCT GENDER FROM ECOMMERCE_DATA;

SELECT DISTINCT Age_Group FROM ECOMMERCE_DATA;

SELECT DISTINCT City FROM ECOMMERCE_DATA;

SELECT DISTINCT State FROM ECOMMERCE_DATA;

SELECT DISTINCT ProductName FROM ECOMMERCE_DATA;

SELECT DISTINCT Category FROM ECOMMERCE_DATA;

SELECT DISTINCT SubCategory FROM ECOMMERCE_DATA;

SELECT DISTINCT Brand FROM ECOMMERCE_DATA;

SELECT DISTINCT DeliveryStatus FROM ECOMMERCE_DATA;

SELECT DISTINCT PaymentMode FROM ECOMMERCE_DATA;

SELECT DISTINCT ReviewTitle FROM ECOMMERCE_DATA;

SELECT DISTINCT Sentiment FROM ECOMMERCE_DATA;

SELECT DISTINCT CustomerSegment FROM ECOMMERCE_DATA;

SELECT DISTINCT ComplaintRaised FROM ECOMMERCE_DATA;

SELECT DISTINCT ResolutionStatus FROM ECOMMERCE_DATA;

UPDATE ECOMMERCE_DATA
SET Rating = (SELECT ROUND(AVG(Rating),0) FROM ECOMMERCE_DATA WHERE Rating IS NOT NULL)
WHERE Rating IS NULL;

ALTER TABLE ECOMMERCE_DATA
ALTER COLUMN COMPLAINTRAISED INT;

UPDATE ECOMMERCE_DATA
SET ComplaintRaised = (SELECT AVG(ComplaintRaised) FROM ECOMMERCE_DATA WHERE ComplaintRaised IS NOT NULL)
WHERE ComplaintRaised IS NULL;

UPDATE ECOMMERCE_DATA
SET Discount = (
    SELECT ROUND(AVG(CAST(Discount AS FLOAT)), 0)
    FROM ECOMMERCE_DATA
    WHERE ISNUMERIC(Discount) = 1)
WHERE Discount IS NULL;

SELECT * FROM ECOMMERCE_DATA;

SELECT COUNT(CUSTOMERID) AS TOTAL_CUSTOMERS, GENDER, AGE_GROUP, SUM(FINAL_AMOUNT) AS TOTAL_REVENUE
FROM ECOMMERCE_DATA
GROUP BY GENDER, AGE_GROUP
ORDER BY TOTAL_REVENUE DESC;

SELECT COUNT(CUSTOMERID) AS TOTAL_CUSTOMERS, City, State, SUM(FINAL_AMOUNT) AS TOTAL_REVENUE
FROM ECOMMERCE_DATA
GROUP BY City, State
ORDER BY TOTAL_REVENUE DESC;

SELECT CATEGORY, MAX(FINAL_AMOUNT) AS MAXIMUM_REVENUE, AVG(RATING) AS AVERAGE_RATING
FROM ECOMMERCE_DATA
GROUP BY Category
ORDER BY MAXIMUM_REVENUE DESC;

SELECT COUNT(CustomerID) AS TOTAL_CUSTOMERS, GENDER, AGE_GROUP, CITY, State
FROM ECOMMERCE_DATA
WHERE DeliveryStatus = 'CANCELLED'
GROUP BY City, State, Age_Group, Gender
ORDER BY TOTAL_CUSTOMERS DESC;

SELECT COUNT(*) AS NUMBER_OF_CUSTOMERS, CITY, CATEGORY, BRAND 
FROM ECOMMERCE_DATA
WHERE DeliveryStatus = 'RETURNED'
GROUP BY CITY, CATEGORY, BRAND
ORDER BY NUMBER_OF_CUSTOMERS DESC;

SELECT COUNT(*) AS NUMBER_OF_COUSTOMER, CITY, CATEGORY, BRAND, SUM(FINAL_AMOUNT) AS TOTAL_REVENUE, SUM(RATING) AS TOTAL_RATING
FROM ECOMMERCE_DATA
WHERE PAYMENTMODE = 'UPI'
GROUP BY CITY, CATEGORY, BRAND
ORDER BY TOTAL_REVENUE DESC;

SELECT COUNT(*) AS NUMBER_OF_COUSTOMER, CITY, CATEGORY, BRAND, SUM(FINAL_AMOUNT) AS TOTAL_REVENUE, SUM(RATING) AS TOTAL_RATING
FROM ECOMMERCE_DATA
WHERE PAYMENTMODE = 'COD'
GROUP BY CITY, CATEGORY, BRAND
ORDER BY TOTAL_REVENUE DESC;

SELECT COUNT(*) AS NUMBER_OF_COUSTOMER, CATEGORY, BRAND, REVIEWTITLE, SUM(RATING) AS TOTAL_RATING
FROM ECOMMERCE_DATA
WHERE Sentiment = 'NEGATIVE'
GROUP BY CATEGORY, BRAND, REVIEWTITLE
ORDER BY TOTAL_RATING DESC;

SELECT COUNT(*) AS NUMBER_OF_COUSTOMER, CATEGORY, BRAND, REVIEWTITLE, SUM(RATING) AS TOTAL_RATING
FROM ECOMMERCE_DATA
WHERE Sentiment = 'POSITIVE'
GROUP BY CATEGORY, BRAND, REVIEWTITLE
ORDER BY TOTAL_RATING DESC;

SELECT TOP 3 COUNT(*) AS NUMBER_OF_COUSTOMER, GENDER, AGE_GROUP, CUSTOMERSEGMENT, SUM(FINAL_AMOUNT) AS TOTAL_REVENUE
FROM ECOMMERCE_DATA
GROUP BY GENDER, AGE_GROUP, CUSTOMERSEGMENT
ORDER BY TOTAL_REVENUE DESC;

SELECT TOP 3 COUNT(*) AS NUMBER_OF_COUSTOMER, GENDER, AGE_GROUP, CUSTOMERSEGMENT, SUM(Rating) AS TOTAL_RATING
FROM ECOMMERCE_DATA
GROUP BY GENDER, AGE_GROUP, CUSTOMERSEGMENT
ORDER BY TOTAL_RATING DESC;

SELECT COUNT(*) AS NUMBER_OF_COUSTOMER, CATEGORY, BRAND, CUSTOMERSEGMENT, SUM(FINAL_AMOUNT) AS TOTAL_REVENUE, SUM(Rating) AS TOTAL_RATING
FROM ECOMMERCE_DATA
GROUP BY CATEGORY, BRAND, CUSTOMERSEGMENT
ORDER BY TOTAL_REVENUE DESC;

ALTER TABLE ECOMMERCE_DATA
ALTER COLUMN ComplaintRaised VARCHAR(3);

UPDATE ECOMMERCE_DATA
SET ComplaintRaised = CASE 
    WHEN ComplaintRaised = '0' THEN 'NO'
    WHEN ComplaintRaised = '1' THEN 'YES'
END;

SELECT COUNT(*) AS NUMBER_OF_CUSTOMER, CATEGORY, BRAND, CUSTOMERSEGMENT, SUM(FINAL_AMOUNT) AS TOTAL_REVENUE, SUM(Rating) AS TOTAL_RATING
FROM ECOMMERCE_DATA
WHERE ComplaintRaised = 'YES'
GROUP BY CATEGORY, BRAND, CUSTOMERSEGMENT
ORDER BY TOTAL_REVENUE DESC;
 























